[features]
seeds = false
[programs.localnet]
simple_stake = "4wK5hPs97SX8Mb3fAwbz6nsBkPw6u7vPxGvUsc1jWCh6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bob/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait=10000
